# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kinpira/kinpira.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kinpira || ORIG_REF_NAME==kinpira}]

# IP: bd/kinpira/ip/kinpira_processing_system7_0_0/kinpira_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kinpira_processing_system7_0_0 || ORIG_REF_NAME==kinpira_processing_system7_0_0}]

# IP: bd/kinpira/ip/kinpira_kinpira_0_0/kinpira_kinpira_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kinpira_kinpira_0_0 || ORIG_REF_NAME==kinpira_kinpira_0_0}]

# IP: bd/kinpira/ip/kinpira_processing_system7_0_axi_periph_0/kinpira_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kinpira_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==kinpira_processing_system7_0_axi_periph_0}]

# IP: bd/kinpira/ip/kinpira_rst_processing_system7_0_100M_0/kinpira_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kinpira_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==kinpira_rst_processing_system7_0_100M_0}]

# IP: bd/kinpira/ip/kinpira_auto_pc_0/kinpira_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kinpira_auto_pc_0 || ORIG_REF_NAME==kinpira_auto_pc_0}]

# XDC: bd/kinpira/ip/kinpira_processing_system7_0_0/kinpira_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kinpira_processing_system7_0_0 || ORIG_REF_NAME==kinpira_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/kinpira/ip/kinpira_rst_processing_system7_0_100M_0/kinpira_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kinpira_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==kinpira_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/kinpira/ip/kinpira_rst_processing_system7_0_100M_0/kinpira_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kinpira_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==kinpira_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/kinpira/ip/kinpira_rst_processing_system7_0_100M_0/kinpira_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/kinpira/ip/kinpira_auto_pc_0/kinpira_auto_pc_0_ooc.xdc

# XDC: bd/kinpira/kinpira_ooc.xdc
