# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /ram/home/work/takau/kinpira/zedboard/zedboard.cache/wt [current_project]
set_property parent.project_path /ram/home/work/takau/kinpira/zedboard/zedboard.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /ram/home/work/takau/kinpira/ip_repo/kinpira_1.0
  /ram/home/work/takau/kinpira/ip_repo/kinpira_1.0
  /ram/home/work/takau/kinpira/ip_repo/kinpira_1.0
  /ram/home/work/takau/kinpira/ip_repo/kinpira_1.0
  /ram/home/work/takau/kinpira/ip_repo/kinpira_1.0
  /ram/home/work/takau/kinpira/ip_repo/ninjin_1.0
} [current_project]
add_files /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/kinpira.bd
set_property used_in_implementation false [get_files -all /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/ip/kinpira_processing_system7_0_0/kinpira_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/ip/kinpira_rst_processing_system7_0_100M_0/kinpira_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/ip/kinpira_rst_processing_system7_0_100M_0/kinpira_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/ip/kinpira_rst_processing_system7_0_100M_0/kinpira_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/ip/kinpira_auto_pc_0/kinpira_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/kinpira_ooc.xdc]
set_property is_locked true [get_files /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/kinpira.bd]

read_verilog -library xil_defaultlib /ram/home/work/takau/kinpira/zedboard/zedboard.srcs/sources_1/bd/kinpira/hdl/kinpira_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top kinpira_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef kinpira_wrapper.dcp

catch { report_utilization -file kinpira_wrapper_utilization_synth.rpt -pb kinpira_wrapper_utilization_synth.pb }
