webtalk_init -webtalk_dir /ram/home/work/takau/kinpira/zedboard/zedboard.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "水 11 30 09:38:50 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vv7pjbjh4qckurkbkscl6i3thh" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1480466246000" -context "sdk\\\\hardware/1480466246000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1480466246000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1480466246000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1480466246000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1480466246000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1480466246000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1480466246000"
webtalk_add_data -client sdk -key uid -value "1480466271000" -context "sdk\\\\bsp/1480466271000"
webtalk_add_data -client sdk -key hwid -value "1480466246000" -context "sdk\\\\bsp/1480466271000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1480466271000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1480466271000"
webtalk_add_data -client sdk -key uid -value "1480466283000" -context "sdk\\\\application/1480466283000"
webtalk_add_data -client sdk -key hwid -value "1480466246000" -context "sdk\\\\application/1480466283000"
webtalk_add_data -client sdk -key bspid -value "1480466271000" -context "sdk\\\\application/1480466283000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1480466283000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1480466283000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1480466283000"
webtalk_transmit -clientid 1012371468 -regid "" -xml /ram/home/work/takau/kinpira/zedboard/zedboard.sdk/webtalk/usage_statistics_ext_sdk.xml -html /ram/home/work/takau/kinpira/zedboard/zedboard.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /ram/home/work/takau/kinpira/zedboard/zedboard.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
